### PR TITLE
feat: Added the abilty to transfer variables when using postMessage

### PR DESCRIPTION
**Pull request by ghost**
MessageChannel is often used when passing data using postMessage to a Worker so it can reply to the origin therefore I added the ability to pass it to the pseudo worker.

https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel
https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

### CODE REVIEW

**Comment by nolanlawson** [comment]
Thanks for the PR! It appears the tests may be failing due to missing Saucelabs credentials. I'll try to rerun with my credentials.

**Comment by bennycode** [comment]
@nolanlawson Have you tried rerunning the tests with your Saucelabs credentials?

**Comment by bennycode** [comment]
@nolanlawson Any updates from your end?

**Comment by bennycode** [comment]
@nolanlawson Another week over. Have you been notified about this change here?

**Comment by nolanlawson** [comment]
Sorry for the delay! Tests seem passing after some tweaks (#20), I will merge and publish soon. Thanks!

**Comment by nolanlawson** [comment]
Merged as 78c94269d9578c142bf375616fe09bbecd21f883 and 3e5cc79e1c2cdbe818541d42a3883c69a154bde2

**Comment by nolanlawson** [comment]
Published in v1.3.0

**Pull request closed without merging**
